const allHooks = [
    "useDocumentTitle",
    "useDefault",
    "useToggle",
    "usePrevious",
    "usePreferredLanguage",
    "useFavicon",
    "useCopyToClipboard",
    "useInterval",
    "useCounter",
    "useLockBodyScroll",
    "useQueue",
    "useTimeout",
    "useWindow",
    "useVisibilityChange",
    "useList",
    "useObjectState",
    "useDebounce",
    "useContinuousRetry",
    "useHistoryState",
    "useEventListener",
    "useRandomInterval",
    "useMediaQuery",
    "useIntervalWhen",
    "useMouse",
    "useClickAway",
    "useWindowScroll",
    "useLogger",
    "useOrientation",
    "useBattery",
    "usePageLeave",
    "useKeyPress",
    "useThrottle",
    "useIdle",
    "useFetch",
    "useCountdown",
    "useGeolocation",
    "useLocalStorage",
    "useSessionStorage",
    "useIsClient"
]

export default allHooks


